services:
  - type: web
    name: cat-money
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./twse_filter.db
      - key: CORS_ORIGINS
        value: "*"
